version: '3.4'
services:
  playground:
    build:
      context: playground/
      dockerfile: Dockerfile
    ports:
    - "8000:8000"
    links:
      - redis
      - postgres
    depends_on:
      - redis
      - postgres
    volumes:
      - ./playground:/app
    command: bash -c "chmod +x entrypoint.sh && ./entrypoint.sh"
    environment:
      - DATABASE_HOST=postgres

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  # queue-a:
  #   build:
  #     context: playground/
  #     dockerfile: Dockerfile.worker
  #   environment:
  #     - WORKER_QUEUE=queue_a
  #     - WORKER_NAME=worker_A
  #   depends_on:
  #     - web

  # queue-b:
  #   build:
  #     context: playground/
  #     dockerfile: Dockerfile.worker
  #   environment:
  #     - WORKER_QUEUE=queue_b
  #     - WORKER_NAME=worker_B
  #   depends_on:
  #     - web

  # queue-c:
  #   build:
  #     context: playground/
  #     dockerfile: Dockerfile.worker
  #   environment:
  #     - WORKER_QUEUE=queue_c
  #     - WORKER_NAME=worker_C
  #   depends_on:
  #     - web

  # scheduler:
  #   build:
  #     context: playground/
  #     dockerfile: Dockerfile.worker
  #   depends_on:
  #     - web

  # queue-monitor:
  #   image: mher/flower
  #   command: flower --basic_auth=${QUEUE_MONITOR_USERNAME}:${QUEUE_MONITOR_PASSWORD} --address=0.0.0.0 --port=5555 --broker=redis://redis:6379
  #   ports:
  #     - '5555:5555'

volumes:
  postgres-data:
